---
- name: User Administration
  hosts: all
  tasks:
  - name: Create a /home/sales directory
    file:
     path: /home/sales
     state: directory
  - name: Create a user and assign different home directory
    user:
     name: oliver
     home: /home/sales/oliver



...




