---
- name: Storage Administration
  hosts: 192.168.100.11 
  tasks:
  - name: Create a partition
    parted:
     device: /dev/sdb
     number: 1
     state: present
     part_end: 1GiB
     
  - name: Assign File System
    filesystem:
     fstype: ext4
     dev: /dev/sdb1
     
  - name: Create a directory to mount it
    file:
     path: /data
     state: directory

  - name: Mount it on /data
    mount:
     fstype: ext4
     src: /dev/sdb1
     path: /data
     state: mounted
...

