---
- name: User Administration
  hosts: servers 
  vars_files:
    - secret.yml
  tasks:
  - name: Create a user "{{ username }}"
    user:
     name: "{{ username }}"
     password: "{{ pass }}"
     state: present
...
