---
- name: User Administration
  hosts: servers 
  tasks:
  - name: Create a user "{{ users.user1.name }}"
    user:
     name: "{{ users.user1.name }}"
     comment: "{{ users.user1.comment  }}"
     shell: /bin/sh
  - name: Create a user "{{ users.user2.name }}" 
    user:
     name: "{{ users.user2.name }}"
     comment: "{{ users.user2.comment }}"
     shell: /bin/sh
...
